export enum CandidateStatusEnum {
  OPEN = "OPEN",
  WAITING_FOR_INTERVIEW = "WAITING_FOR_INTERVIEW",
  CANCELLED_INTERVIEW = "CANCELLED_INTERVIEW",
  PASSED_INTERVIEW = "PASSED_INTERVIEW",
  FAILED_INTERVIEW = "FAILED_INTERVIEW",
  WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL",
  APPROVED_OFFER = "APPROVED_OFFER",
  REJECTED_OFFER = "REJECTED_OFFER",
  WAITING_FOR_RESPONSE = "WAITING_FOR_RESPONSE",
  ACCEPTED_OFFER = "ACCEPTED_OFFER",
  DECLINED_OFFER = "DECLINED_OFFER",
  CANCELLED_OFFER = "CANCELLED_OFFER",
  BANNED = "BANNED",
}

export enum HighestLevelEnum {
  HIGH_SCHOOL = "HIGH_SCHOOL",
  BACHELOR_DEGREE = "BACHELOR_DEGREE",
  MASTER_DEGREE = "MASTER_DEGREE",
  PHD = "PHD",
}

export enum PositionEnum {
  BACKEND_DEVELOPER = "BACKEND_DEVELOPER",
  BUSINESS_ANALYST = "BUSINESS_ANALYST",
  TESTER = "TESTER",
  HR = "HR",
  PROJECT_MANAGER = "PROJECT_MANAGER",
  NOT_AVAILABLE = "NOT_AVAILABLE",
}
