// BACKEND_DEVELOPER, BUSINESS_ANALYST, TESTER, HR, PROJECT_MANAGER, NOT_AVAILABLE
export enum PositionEnum {
  BACKEND_DEVELOPER = "BACKEND_DEVELOPER",
  BUSINESS_ANALYST = "BUSINESS_ANALYST",
  TESTER = "TESTER",
  HR = "HR",
  PROJECT_MANAGER = "PROJECT_MANAGER",
  NOT_AVAILABLE = "NOT_AVAILABLE",
}
